### ISSUE TITLE
Use of cache

### ISSUE THREAD

**Issue by tsuu32** [y-yu/install-tex-travis#18]
日本語で失礼します。

現在READMEのHow to useではcacheを使うことが書かれています。
```yml
cache:
  directories:
    - $HOME/texlive
    - $HOME/.texlive
    - $HOME/texmf
```

しかし、`if [ ! -d "$HOME/texlive" ]; then`のようなcacheがあるかどうかで動作が変わるコードは`install-tex.sh`にはありません。したがって、cacheは作られるが毎回`./install-tl`するような動作になってしまっていると思います。

また、ユーザが以下のように.travis.ymlを書くとすると、cacheが使われますが、PATHの設定も行われないためうまくいきません。
```yml
install:
  - if [ ! -d "$HOME/texlive" ]; then . ./install-tex.sh; fi
```

以下のどれかの対応が好ましいと思いますがどうでしょうか。
* install-tex.shでPATHの設定以外を`if [ ! -d "$HOME/texlive" ]; then`で囲む
* PATHの設定を別スクリプトにして、cacheを使いたいユーザは`if [ ! -d "$HOME/texlive" ]; then . ./install-tex.sh; fi`を書く
* How to useからcacheを消す
